name: ci pipeline 
on:
   push:
      branches:
        - main 
        - red 
   pull_request:
       branches:
         - main 
         - red
jobs:
   red:
     runs-on: ubuntu-latest 
     steps:
      - name: constructing pipeline
        uses: actions/checkout@v4  
      - name: say hello 
        run: echo "Hello, world!"